import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import ClientWrapper

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
        style={{
          backgroundImage: "url('/fon.jpg')",
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundAttachment: "fixed",
        }}
      >
        <div className="min-h-screen flex flex-col">
          {/* Всё, что зависит от Zustand/auth — внутрь ClientWrapper */}
          <ClientWrapper>
            {children}
          </ClientWrapper>

          <Script
            src="https://www.cryptopro.ru/sites/default/files/products/cades/cadesplugin_api.js"
            strategy="beforeInteractive"
          />
        </div>
      </body>
    </html>
  );
}
