import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Script from "next/script";

import { useEffect } from "react";
import { useAuthStore } from "@/store/auth";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const init = useAuthStore((s) => s.init)
  useEffect(() => {
    init();
  }, [init]);
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`} style={{
          backgroundImage: "url('/fon.jpg')",
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundAttachment: "fixed", // чтобы фон оставался на месте при скролле
        }}
        >
        <div className="min-h-screen flex flex-col">

          <Header />
          <main className="flex-1 container mx-auto px-4 pt-20 pb-6 text-center">{children}</main>
          <Script
            src="https://www.cryptopro.ru/sites/default/files/products/cades/cadesplugin_api.js"
            strategy="beforeInteractive"
          />
        </div>    
      </body>
    </html>
  );
}
